### ISSUE TITLE
Connecting a Router to the Server

### ISSUE THREAD

**Issue by Jacobingalls** [dwimberger/crowd-radius-server#2]
I set up the radius server to allow connections from my router,
using RadLogin i verified that the server is working
<addr>
20:48:36.439 [Thread-2] DEBUG net.wimpi.crowd.radius.RadiusService - Retrieving secret for client 192.168.1.145 isavail=true
20:48:36.440 [Thread-2] DEBUG net.wimpi.crowd.radius.RadiusService - Retrieving secret for client 192.168.1.145 isavail=true
20:48:36.440 [Thread-2] DEBUG net.wimpi.crowd.radius.RadiusService - PacketReceiver()::run()::Received radius packet to queue.
20:48:36.543 [pool-1-thread-3] DEBUG net.wimpi.crowd.radius.RadiusService - send response: Access-Accept, ID 11 to /192.168.1.145:54413
20:48:36.544 [pool-1-thread-3] DEBUG net.wimpi.crowd.radius.RadiusService - Retrieving secret for client 192.168.1.145 isavail=true
</addr>

but when the router makes the request

<addr>21:04:42.251 [Thread-2] DEBUG net.wimpi.crowd.radius.RadiusService - Retrieving secret for client 192.168.1.1 isavail=true
21:04:42.251 [Thread-2] DEBUG net.wimpi.crowd.radius.RadiusService - Retrieving secret for client 192.168.1.1 isavail=true
21:04:42.252 [Thread-2] ERROR net.wimpi.crowd.radius.RadiusService - PacketReceiver()::run()
org.tinyradius.util.RadiusException: Access-Request: User-Password or CHAP-Password/CHAP-Challenge missing
    at org.tinyradius.packet.AccessRequest.decodeRequestAttributes(AccessRequest.java:160) ~[crowd-radius-server-1.0-SNAPSHOT.jar:na]
    at org.tinyradius.packet.RadiusPacket.decodePacket(RadiusPacket.java:886) ~[crowd-radius-server-1.0-SNAPSHOT.jar:na]
    at org.tinyradius.packet.RadiusPacket.decodeRequestPacket(RadiusPacket.java:538) ~[crowd-radius-server-1.0-SNAPSHOT.jar:na]
    at net.wimpi.crowd.radius.RadiusService$PacketReceiver.run(RadiusService.java:449) ~[crowd-radius-server-1.0-SNAPSHOT.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_60]</addr>

Thanks,
Jacob

**Comment by bassrock** [comment]
@Jacobingalls did you figure this out I am getting the same error

**Comment by Jacobingalls** [comment]
No, we ended up changing the structure of our stack. We now have Microsoft AD as the Authoritative user store, and Crowd running off that.

**Comment by dwimberger** [comment]
The current implementation will only work for PAP (it's commented in the source, I'll add a note to the Wiki). Usually one requires access to the password in cleartext to do CHAP, which is not possible through the Crowd REST API.
